
services:
  # Contenedor que alojará el servidor NATS - La propia imagen de 
  # DockerHub tiene un servidor NATS  
  servidor-nats:
    restart: on-failure
    image: nats
    ports:
      - "4222:4222"
      - "6222:6222"
      - "8222:8222"
  # Volumen para recoger ip del server-NATS
    volumes:
      - volumenNATS:/data

  # Contenedor que alojará el cliente Python de NATS - Este
  # se suscribirá y enviará mensajes a un tópico
  cliente-nats:
    restart: on-failure
    build: 
        context: .
        dockerfile: Dockerfile
    depends_on:
      - servidor-nats
    volumes:
      - volumenNATS:/data
        

volumes:
        volumenNATS:
