###################################################################
#      DEPLOYMENT PARA CLIENTE NATS PUBLISHER - KUBERNETES       #
###################################################################

# Version
apiVersion: apps/v1
# Especificar tipo de objeto Kubernetes, en este caso, 'Deployment'
kind: Deployment

metadata:
  # Nombre del objeto Deployment
  name: deployment-cliente-pub
# Especificaciones
spec:
  # Numero de Pods idénticos
  replicas: 1
  selector:
    matchLabels:
      # Especificar label identificador
      modulo: cliente-pub
  # Plantilla con la que se crearán los Pods 
  template:
    metadata:
      labels:
       # Label identificador, tiene que coincidir con el de arriba
       modulo: cliente-pub
    spec:
      # Especificaciones del contenedor a crear
      containers:
      # Nombre del contenedor
      - name: pod-cliente-pub
        # Imagen 
        image: alopezmena/cliente-nats-pub
        # Mapeo de puertos->Se expondrán los siguientes puertos
        ports:
        - containerPort: 4222
        - containerPort: 6222
        - containerPort: 8222
