###################################################################
#      DEPLOYMENT PARA CLIENTE NATS SUBSCRIBER - KUBERNETES       #
###################################################################

# Version
apiVersion: apps/v1
# Especificar tipo de objeto Kubernetes --> Deployment
# Este crea un conjunto de Pods y monitoriza su estado
kind: Deployment

# Sección METADATA
#------------------
metadata:

  labels:
    modulo: sub-cliente-nats
  # Nombre del objeto Deployment
  name: sub-cliente-nats
  
# Sección SPEC
#------------------
spec:
  # Numero de Pods idénticos que se generarán con el deployment
  replicas: 1
  selector:
    matchLabels:
      # Especificar label identificador
      modulo: sub-cliente-nats

  template:
    metadata:
      # Label identificador, tiene que coincidir con el de arriba
      labels:
        modulo: sub-cliente-nats
    # Especificaciones del contenedor a crear
    spec:
      containers:
        # Imagen correspondiente a SUBSCRIBER en Docker Hub
        - image: alopezmena/cliente-nats-sub
          # Nombre del contenedor
          name: sub-cliente-nats   
          
          # En esta parte se concreta la configuración del PV
          volumeMounts:
            # Punto de montaje en el contenedor
            - mountPath: /logNats
            # Nombre del Volumen [*]
              name: volumen-nats
              
      # Politica de reinicio: Always
      # Reiniciar siempre. Si se ha parado manualmente, se 
      # reinicia cuando se reinicie el servicio Docker
      restartPolicy: Always
      
      # Sección para volúmenes
      volumes:
        # Nombre del volumen  [*]
        - name: volumen-nats
        # Asignar la reclamación de volumen persistente
          persistentVolumeClaim:
            claimName: volumen-nats
            
########################################################################
# [*] Ambos campos deben coincidir. Debe coincidir además con el
# nombre asignado en el fichero de configuración de la solicitud.

